version: '3.8'
services:
  koboldcpp:
    container_name: koboldcpp
    restart: always
    volumes:
      - './models:/app/models'
    ports:
      - '8080:80'
    image: 'koboldcpp:latest'
    command: [ "/app/koboldcpp.py", "--model_path", "/app/models/Wizard-Vicuna-13B-Uncensored-GPTQ", "--port", "80" ]